schema_version = "1.0.0"

id = "NodePie"
version = "1.2.38"
name = "Node Pie"
tagline = "Add nodes faster with a pie menu"
maintainer = "Andrew Stevenson"
type = "add-on"
website = "https://blenderartists.org/t/node-pie-menu-free-addon/1402871"
tags = ["User Interface", "Node"]

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Reading and writing config files"